// <auto-generated />
using System;
using System.Collections.Generic;
using CuidaBem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CuidaBem.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260206034531_AddOrientacoes")]
    partial class AddOrientacoes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CuidaBem.Models.Cuidador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HashPassword")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Cuidadores");
                });

            modelBuilder.Entity("CuidaBem.Models.InsulinaDosagem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("AlertaCritico")
                        .HasColumnType("boolean");

                    b.Property<bool>("Aplicar")
                        .HasColumnType("boolean");

                    b.Property<string>("ContatoEmergencia")
                        .HasColumnType("text");

                    b.Property<int>("DoseUi")
                        .HasColumnType("integer");

                    b.Property<int?>("HgtMaximo")
                        .HasColumnType("integer");

                    b.Property<int>("HgtMinimo")
                        .HasColumnType("integer");

                    b.Property<int>("MedicamentoId")
                        .HasColumnType("integer");

                    b.Property<string>("TelefoneEmergencia")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("MedicamentoId");

                    b.ToTable("InsulinaDosagens");
                });

            modelBuilder.Entity("CuidaBem.Models.Medicamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Dosagem")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Instrucoes")
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Unidade")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Medicamentos");
                });

            modelBuilder.Entity("CuidaBem.Models.MedicamentoHorario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AntesOuDepois")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<string>("ContextoRefeicao")
                        .HasColumnType("text");

                    b.PrimitiveCollection<int[]>("DiasSemana")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<TimeSpan>("Horario")
                        .HasColumnType("interval");

                    b.Property<int>("MedicamentoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MedicamentoId");

                    b.ToTable("MedicamentoHorarios");
                });

            modelBuilder.Entity("CuidaBem.Models.OrientacaoExecucao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CuidadorId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ExecutadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Observacao")
                        .HasColumnType("text");

                    b.Property<int>("ReferenciaId")
                        .HasColumnType("integer");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CuidadorId");

                    b.ToTable("OrientacaoExecucoes");
                });

            modelBuilder.Entity("CuidaBem.Models.ProcedimentoRecorrente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("DataFim")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Instrucoes")
                        .HasColumnType("text");

                    b.Property<int>("IntervaloDias")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ProcedimentosRecorrentes");
                });

            modelBuilder.Entity("CuidaBem.Models.Registro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CuidadorId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Data")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DoseLentaAnte")
                        .HasColumnType("integer");

                    b.Property<int>("DoseRapida")
                        .HasColumnType("integer");

                    b.Property<int>("HgtAntes")
                        .HasColumnType("integer");

                    b.Property<int>("HgtDepois")
                        .HasColumnType("integer");

                    b.Property<TimeSpan>("HoraAntes")
                        .HasColumnType("interval");

                    b.Property<TimeSpan>("HoraDepois")
                        .HasColumnType("interval");

                    b.PrimitiveCollection<List<string>>("MedicamentosTomados")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Observacao")
                        .HasColumnType("text");

                    b.Property<int>("PressaoDiastolica")
                        .HasColumnType("integer");

                    b.Property<int>("PressaoSistolica")
                        .HasColumnType("integer");

                    b.Property<string>("Refeicao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Saturacao")
                        .HasColumnType("integer");

                    b.Property<decimal>("Temperatura")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("CuidadorId");

                    b.ToTable("Registros");
                });

            modelBuilder.Entity("CuidaBem.Models.InsulinaDosagem", b =>
                {
                    b.HasOne("CuidaBem.Models.Medicamento", "Medicamento")
                        .WithMany("DosagensVariaveis")
                        .HasForeignKey("MedicamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Medicamento");
                });

            modelBuilder.Entity("CuidaBem.Models.MedicamentoHorario", b =>
                {
                    b.HasOne("CuidaBem.Models.Medicamento", "Medicamento")
                        .WithMany("Horarios")
                        .HasForeignKey("MedicamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Medicamento");
                });

            modelBuilder.Entity("CuidaBem.Models.OrientacaoExecucao", b =>
                {
                    b.HasOne("CuidaBem.Models.Cuidador", "Cuidador")
                        .WithMany()
                        .HasForeignKey("CuidadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cuidador");
                });

            modelBuilder.Entity("CuidaBem.Models.Registro", b =>
                {
                    b.HasOne("CuidaBem.Models.Cuidador", "Cuidador")
                        .WithMany("Registros")
                        .HasForeignKey("CuidadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cuidador");
                });

            modelBuilder.Entity("CuidaBem.Models.Cuidador", b =>
                {
                    b.Navigation("Registros");
                });

            modelBuilder.Entity("CuidaBem.Models.Medicamento", b =>
                {
                    b.Navigation("DosagensVariaveis");

                    b.Navigation("Horarios");
                });
#pragma warning restore 612, 618
        }
    }
}
