// <auto-generated />
using System;
using CuidaBem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CuidaBem.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260201011455_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CuidaBem.Api.Models.Registro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Data")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DoseLentaAnte")
                        .HasColumnType("integer");

                    b.Property<int>("DoseRapida")
                        .HasColumnType("integer");

                    b.Property<int>("HgtAntes")
                        .HasColumnType("integer");

                    b.Property<int>("HgtDepois")
                        .HasColumnType("integer");

                    b.Property<TimeSpan>("HoraAntes")
                        .HasColumnType("interval");

                    b.Property<TimeSpan>("HoraDepois")
                        .HasColumnType("interval");

                    b.Property<string>("Observacao")
                        .HasColumnType("text");

                    b.Property<string>("Refeicao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Registros");
                });
#pragma warning restore 612, 618
        }
    }
}
