// <auto-generated />
using System;
using System.Collections.Generic;
using CuidaBem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CuidaBem.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260203034947_AddMedicamentosAndVitals")]
    partial class AddMedicamentosAndVitals
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CuidaBem.Models.Cuidador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HashPassword")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Cuidadores");
                });

            modelBuilder.Entity("CuidaBem.Models.Registro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CuidadorId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Data")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DoseLentaAnte")
                        .HasColumnType("integer");

                    b.Property<int>("DoseRapida")
                        .HasColumnType("integer");

                    b.Property<int>("HgtAntes")
                        .HasColumnType("integer");

                    b.Property<int>("HgtDepois")
                        .HasColumnType("integer");

                    b.Property<TimeSpan>("HoraAntes")
                        .HasColumnType("interval");

                    b.Property<TimeSpan>("HoraDepois")
                        .HasColumnType("interval");

                    b.PrimitiveCollection<List<string>>("MedicamentosTomados")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Observacao")
                        .HasColumnType("text");

                    b.Property<int>("PressaoDiastolica")
                        .HasColumnType("integer");

                    b.Property<int>("PressaoSistolica")
                        .HasColumnType("integer");

                    b.Property<string>("Refeicao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Saturacao")
                        .HasColumnType("integer");

                    b.Property<decimal>("Temperatura")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("CuidadorId");

                    b.ToTable("Registros");
                });

            modelBuilder.Entity("CuidaBem.Models.Registro", b =>
                {
                    b.HasOne("CuidaBem.Models.Cuidador", "Cuidador")
                        .WithMany("Registros")
                        .HasForeignKey("CuidadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cuidador");
                });

            modelBuilder.Entity("CuidaBem.Models.Cuidador", b =>
                {
                    b.Navigation("Registros");
                });
#pragma warning restore 612, 618
        }
    }
}
